### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils' while pnpm install

### ISSUE THREAD

**Issue by VictorECDSA** [latticexyz/skystrife-public#2]
Please help ! Appreciate !

```
% pwd
/Users/xxx/Documents/Workspace/Solidity/latticexyz/skystrife-public/packages/contracts
```

```
% pnpm install                 
Scope: all 10 workspace projects
../..                                    |  WARN  There are cyclic workspace dependencies: /Users/xxx/Documents/Workspace/Solidity/latticexyz/skystrife-public/packages/client, /Users/xxx/Documents/Workspace/Solidity/latticexyz/skystrife-public/packages/contracts
../..                                    |    +1543 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
../..                                    | Progress: resolved 1543, reused 1522, downloaded 0, added 0, done
../../node_modules/.pnpm/node-pty@1.0.0/node_modules/node-pty: Running install script, failed in 392ms
.../node-pty@1.0.0/node_modules/node-pty install$ node-gyp rebuild
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.4.1
│ gyp info using node@18.19.0 | darwin | arm64
│ gyp info find Python using Python version 3.12.0 found at "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3"
│ gyp info spawn /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
│ gyp info spawn args [
│ gyp info spawn args   '/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/xxx/Documents/Workspace/Solidity/latticexyz/skystrife-public/node_modules/.pnpm/node-pty@1.0.0/node_mod…
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/xxx/Library/Caches/node-gyp/18.19.0/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/Users/xxx/Library/Caches/node-gyp/18.19.0',
│ gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=/Users/xxx/Library/Caches/node-gyp/18.19.0/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/Users/xxx/Documents/Workspace/Solidity/latticexyz/skystrife-public/node_modules/.pnpm/node-…
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ Traceback (most recent call last):
│   File "/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
│     import gyp  # noqa: E402
│     ^^^^^^^^^^
│   File "/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
│     import gyp.input
│   File "/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
│     from distutils.version import StrictVersion
│ ModuleNotFoundError: No module named 'distutils'
│ gyp ERR! configure error 
│ gyp ERR! stack Error: `gyp` failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/configure.js:325:16)
│ gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
│ gyp ERR! System Darwin 23.1.0
│ gyp ERR! command "/Users/xxx/.nvm/versions/node/v18.19.0/bin/node" "/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/n…
│ gyp ERR! cwd /Users/xxx/Documents/Workspace/Solidity/latticexyz/skystrife-public/node_modules/.pnpm/node-pty@1.0.0/node_modules/node-…
│ gyp ERR! node -v v18.19.0
│ gyp ERR! node-gyp -v v9.4.1
│ gyp ERR! not ok 
└─ Failed in 392ms at /Users/xxx/Documents/Workspace/Solidity/latticexyz/skystrife-public/node_modules/.pnpm/node-pty@1.0.0/node_modules/node-pty
../../node_modules/.pnpm/bigint-buffer@1.1.5/node_modules/bigint-buffer: Running install script...
../../node_modules/.pnpm/better-sqlite3@9.3.0/node_modules/better-sqlite3: Running install script...
../../node_modules/.pnpm/node-datachannel@0.5.3/node_modules/node-datachannel: Running install script...
../../node_modules/.pnpm/keccak@3.0.4/node_modules/keccak: Running install script...
 ELIFECYCLE  Command failed with exit code 1.
```

```
% node -v
v18.19.0
% pnpm -v
8.11.0
% npm -v
4.6.1
% sw_vers
ProductName:		macOS
ProductVersion:		14.1.2
BuildVersion:		23B92
```

**Comment by VictorECDSA** [comment]
Oh I have fixed it after

```
pip3 install setuptools
```
